# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Levin Güver
description: >- # this means to ignore newlines until "baseurl:"
  I am Levin Güver, a Philosophy Student at the UZH.
baseurl: "" # the subpath of the site
url: "https://levinguever.com" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"
remote_theme: eliottvincent/bay

header:
  pages:
    - name: About
      slug: /
    - name: Research
    - name: Teaching
    # - name: Other
    
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: levin.guever[at]gmail.com
      link: mailto:levin.guever@hotmail.de
  follow:
    - name: Researchgate
      link: https://researchgate.net/profile/levin-guever
    - name: Twitter
      link: https://twitter.com/levinguever


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
